(()=>{
  "use strict";
  const STORE_KEY="bet-tracker-live-v1";
  const PDFJS="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.min.mjs";
  const PDFWORKER="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.7.284/build/pdf.worker.min.mjs";
  const TESS_SRC="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js";
  let pdfModule=null,tessPromise=null,worker=null,current=null,paddySnapshot=null,paddyReadHandler=null;
  const money=n=>new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(Number(n)||0);
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const norm=s=>String(s||"").trim().toLowerCase();
  const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  const isoDate=(d,m,y)=>`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
  const dateKey=s=>Number(String(s||"").replace(/-/g,""))||0;
  const inRange=(d,from,to)=>d>=from&&d<=to;
  function readData(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||"null")}catch{return null}}
  async function saveData(d){
    localStorage.setItem(STORE_KEY,JSON.stringify(d));
    try{const client=window.btSupabase;if(!client)return;const sess=await client.auth.getSession();const uid=sess.data?.session?.user?.id;if(uid)await client.from("bet_tracker_state").upsert({user_id:uid,data:d,updated_at:new Date().toISOString()},{onConflict:"user_id"})}catch(e){console.warn("Bet365 cloud sync",e)}
  }
  async function loadPdf(){if(pdfModule)return pdfModule;pdfModule=await import(PDFJS);pdfModule.GlobalWorkerOptions.workerSrc=PDFWORKER;return pdfModule}
  function loadTesseract(){
    if(window.Tesseract)return Promise.resolve(window.Tesseract);
    if(tessPromise)return tessPromise;
    tessPromise=new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=TESS_SRC;s.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error("OCR reader failed to load."));s.onerror=()=>reject(new Error("OCR reader failed to load."));document.head.appendChild(s)});
    return tessPromise;
  }
  async function getWorker(status){
    if(worker)return worker;
    const T=await loadTesseract();
    status.textContent="Loading Bet365 OCR reader…";
    worker=await T.createWorker("eng",1,{logger:m=>{if(m?.status&&typeof m.progress==="number"&&m.status.includes("recognizing"))status.textContent=`Reading Bet365 statement… ${Math.round(m.progress*100)}%`}});
    await worker.setParameters({tessedit_pageseg_mode:"6",preserve_interword_spaces:"1"});
    return worker;
  }
  function parseDateToken(raw){
    const s=String(raw||"").replace(/[O]/gi,"0").replace(/[Il]/g,"1").replace(/^[^0-9]+|[^0-9]+$/g,"");
    let m=s.match(/^(\d{2})[\/|\\.\-]?(\d{2})[\/|\\.\-]?(\d{4})$/);if(!m)return null;
    const d=Number(m[1]),mo=Number(m[2]),y=Number(m[3]);if(d<1||d>31||mo<1||mo>12||y<2020||y>2100)return null;return isoDate(d,mo,y)
  }
  function extractDates(text){
    const out=[];const s=String(text||"").replace(/[O]/gi,"0").replace(/[Il]/g,"1");
    for(const m of s.matchAll(/(?:^|\D)(\d{2}[\/|\\.\-]?\d{2}[\/|\\.\-]?\d{4})(?=\D|$)/g)){const d=parseDateToken(m[1]);if(d)out.push(d)}
    return out
  }
  async function renderCrop(doc,pageNo,scale,y0,y1,x0=.012,x1=.995){
    const page=await doc.getPage(pageNo),vp=page.getViewport({scale}),full=document.createElement("canvas");full.width=Math.ceil(vp.width);full.height=Math.ceil(vp.height);await page.render({canvasContext:full.getContext("2d",{alpha:false}),viewport:vp}).promise;
    const sx=Math.floor(full.width*x0),sy=Math.floor(full.height*y0),sw=Math.max(1,Math.floor(full.width*(x1-x0))),sh=Math.max(1,Math.floor(full.height*(y1-y0))),c=document.createElement("canvas");c.width=sw;c.height=sh;c.getContext("2d",{alpha:false}).drawImage(full,sx,sy,sw,sh,0,0,sw,sh);full.width=full.height=1;return c
  }
  async function pageDateBounds(doc,pageNo,w){
    const y0=pageNo===1?.56:.01,c=await renderCrop(doc,pageNo,1.45,y0,.95,.01,.22),r=await w.recognize(c),dates=extractDates(r.data?.text);c.width=c.height=1;if(!dates.length)return null;dates.sort();return{oldest:dates[0],newest:dates.at(-1)}
  }
  async function findLastPageForFrom(doc,from,w,status){
    const cache=new Map();async function at(n){if(cache.has(n))return cache.get(n);status.textContent=`Locating ${from.split("-").reverse().join("/")} in ${doc.numPages} pages…`;let b=await pageDateBounds(doc,n,w);if(!b&&n>1)b=await pageDateBounds(doc,n-1,w);cache.set(n,b);return b}
    let lo=1,hi=doc.numPages,ans=0,target=dateKey(from);
    while(lo<=hi){const mid=Math.floor((lo+hi)/2),b=await at(mid);if(!b){hi=mid-1;continue}if(dateKey(b.newest)>=target){ans=mid;lo=mid+1}else hi=mid-1}
    if(!ans){const b=await at(1);if(b&&dateKey(b.oldest)<target)return 0;ans=1}
    return Math.min(doc.numPages,ans+1)
  }
  function lineGroups(words,tol){
    const lines=[];for(const w of [...words].sort((a,b)=>a.cy-b.cy||a.cx-b.cx)){let l=lines.find(q=>Math.abs(q.cy-w.cy)<=tol);if(!l){l={cy:w.cy,words:[]};lines.push(l)}l.words.push(w);l.cy=l.words.reduce((s,x)=>s+x.cy,0)/l.words.length}return lines.sort((a,b)=>a.cy-b.cy)
  }
  function cleanCell(s){return String(s||"").replace(/[|\[\]{}]/g," ").replace(/\s+/g," ").trim()}
  function cellText(words,tol){return lineGroups(words,tol).map(l=>l.words.sort((a,b)=>a.cx-b.cx).map(w=>w.text).join(" ")).join(" ").replace(/\s+/g," ").trim()}
  function normalType(s){const k=norm(s).replace(/[^a-z]/g,"");if(k.includes("games")&&k.includes("stake"))return"Games Stake";if(k.includes("games")&&(k.includes("return")||k.includes("retum")))return"Games Return";if(k.includes("stake"))return"Stake";if(k.includes("return")||k.includes("retum"))return"Return";if(k.includes("deposit"))return"Deposit";if(k.includes("withdraw"))return"Withdrawal";return cleanCell(s)}
  function moneyCell(s){const m=String(s||"").replace(/,/g,"").match(/£?\s*([0-9]+(?:\.[0-9]{1,2})?)/);return m?Number(m[1]):0}
  function fractionFrom(s){const x=String(s||"").replace(/I/g,"/").replace(/l/g,"/");const ms=[...x.matchAll(/(\d{1,4})\s*[\/|]\s*(\d{1,4})/g)];if(!ms.length)return null;const m=ms.at(-1),a=Number(m[1]),b=Number(m[2]);return b>0?{a,b,decimal:1+a/b,text:`${a}/${b}`} : null}
  function resultFrom(s){const m=String(s||"").match(/\b(Won|Lost|Void|Pending)\b/i);return m?m[1][0].toUpperCase()+m[1].slice(1).toLowerCase():""}
  function wordsToRows(data,pageNo,canvasWidth){
    const raw=(data?.words||[]).filter(w=>w?.text?.trim()&&w?.bbox).map(w=>({text:w.text,cx:(w.bbox.x0+w.bbox.x1)/2,cy:(w.bbox.y0+w.bbox.y1)/2,conf:Number(w.confidence??w.conf??0)}));if(!raw.length)return[];
    const W=Number(canvasWidth)||Math.max(...raw.map(w=>w.cx))*1.01,tol=Math.max(7,W*.006),dateWords=raw.filter(w=>w.cx<W*.15),anchors=[];
    for(const l of lineGroups(dateWords,tol)){const t=l.words.sort((a,b)=>a.cx-b.cx).map(w=>w.text).join(" "),m=t.match(/([0-9OIl]{2}[\/|\\.\-]?[0-9OIl]{2}[\/|\\.\-]?[0-9OIl]{4})\s+(\d{1,2}:\d{2}:\d{2})/);if(!m)continue;const date=parseDateToken(m[1]);if(date)anchors.push({cy:l.cy,date,time:m[2]})}
    const b=[0,.145,.285,.365,.60,.71,.79,.895,1.02],names=["dateCell","ref","type","description","oddsCell","resultCell","deductionCell","additionCell"],out=[];
    for(let i=0;i<anchors.length;i++){
      const a=anchors[i],y0=i?((anchors[i-1].cy+a.cy)/2):a.cy-tol*2.2,y1=i+1<anchors.length?((a.cy+anchors[i+1].cy)/2):a.cy+tol*3.0,cells=Object.fromEntries(names.map(n=>[n,[]]));
      for(const w of raw){if(w.cy<y0||w.cy>=y1)continue;const x=w.cx/W;for(let j=0;j<names.length;j++){if(x>=b[j]&&x<b[j+1]){cells[names[j]].push(w);break}}}
      const row={page:pageNo,date:a.date,time:a.time,when:`${a.date}T${a.time}`,confidence:0};let confs=[];for(const n of names){row[n]=cleanCell(cellText(cells[n],tol));confs.push(...cells[n].map(w=>w.conf).filter(Number.isFinite))}row.confidence=confs.length?confs.reduce((s,x)=>s+x,0)/confs.length:0;row.ref=row.ref.replace(/[^A-Za-z0-9]/g,"");row.type=normalType(row.type);row.result=resultFrom(`${row.resultCell} ${row.oddsCell}`);row.deduction=moneyCell(row.deductionCell);row.addition=moneyCell(row.additionCell);row.fraction=fractionFrom(`${row.oddsCell} ${row.resultCell}`);out.push(row)
    }
    return out
  }
  function groupRows(rows){
    const groups=[];let g=null;for(const r of rows){if(!r.type)continue;const monetary=r.deduction>0||r.addition>0,start=!!r.ref||monetary||!g||r.type!==g.type||r.when!==g.when;if(start){if(g)groups.push(g);g={type:r.type,ref:r.ref,date:r.date,time:r.time,when:r.when,rows:[r]}}else g.rows.push(r)}if(g)groups.push(g);return groups
  }
  function mapSport(desc){const p=cleanCell(desc).split(/\s+-\s+/)[0].trim();const k=norm(p);if(k==="soccer")return"Football";if(k.includes("horse")&&k.includes("racing"))return"Horse Racing";if(k==="american football")return"American Football";if(k==="ice hockey")return"Ice Hockey";if(k==="table tennis")return"Table Tennis";if(k==="basketball")return"Basketball";if(k==="tennis")return"Tennis";if(k==="darts")return"Darts";if(k==="golf")return"Golf";if(k==="cricket")return"Cricket";return p||"Other"}
  function stripSport(desc){return cleanCell(desc).replace(/^[^-]{2,30}\s+-\s+/,"").trim()}
  function selectionText(r){let s=cleanCell(r.oddsCell).replace(/\b(Won|Lost|Void|Pending)\b/ig,"").replace(/\d{1,4}\s*[\/|I]\s*\d{1,4}/g,"").replace(/\s+-\s*$/," ").trim();return s}
  function riskType(odds){if(!(odds>0))return"Medium Risk (Evs - 10/1)";if(odds>=101)return"Longshot (100/1+)";if(odds>=11)return"High Risk (10/1+)";if(odds<2)return"Low Risk (Around Evs)";return"Medium Risk (Evs - 10/1)"}
  function buildData(groups,from,to,closingBalance){
    const returns=new Map();for(const g of groups.filter(g=>g.type==="Return"||g.type==="Games Return")){if(!g.ref)continue;const amount=g.rows.find(r=>r.addition>0)?.addition||0;returns.set(g.ref,{amount,group:g})}
    const bets=[];for(const g of groups.filter(g=>g.type==="Stake"||g.type==="Games Stake")){
      if(!inRange(g.date,from,to))continue;const gaming=g.type==="Games Stake",stake=g.rows.find(r=>r.deduction>0)?.deduction||0,ret=returns.get(g.ref),rowResults=g.rows.map(r=>r.result).filter(Boolean),lost=rowResults.includes("Lost"),allVoid=rowResults.length>0&&rowResults.every(x=>x==="Void"),result=lost?"Loss":allVoid?"Void":ret?.amount>0||rowResults.length&&rowResults.every(x=>x==="Won"||x==="Void")?"Win":"Pending",sports=[...new Set(g.rows.map(r=>gaming?"Free Spins":mapSport(r.description)).filter(Boolean))],sport=sports.length===1?sports[0]:(sports.length>1?"Multiple Sports":gaming?"Free Spins":"Other"),parts=g.rows.map(r=>{const d=stripSport(r.description),sel=selectionText(r);return sel&&norm(sel)!==norm(d)?`${d} — ${sel}`:d}).filter(Boolean),description=parts.join(" | "),fracs=g.rows.filter(r=>r.result!=="Void").map(r=>r.fraction),haveAll=fracs.length===g.rows.filter(r=>r.result!=="Void").length&&fracs.every(Boolean);let odds=haveAll?fracs.reduce((p,f)=>p*f.decimal,1):0;if(ret?.amount>0&&stake>0&&!gaming)odds=ret.amount/stake;let type=gaming?"Free Spins":riskType(odds),actualStake=stake;if(!gaming&&stake===0){type=riskType(odds);actualStake=0}const exactReturn=ret?.amount||null,confidence=Math.min(...g.rows.map(r=>r.confidence||0)),review=!g.ref||(!gaming&&!odds)||confidence<65||(!stake&&!exactReturn);const bet={date:g.date,when:g.when,app:"Bet365",sport,type,description,odds:Number(odds||1),stake:Number(actualStake||0),result,sourceRef:g.ref||`ocr-${g.when}-${hash(description)}`,importConfidence:review?"review":"high",ocrConfidence:Math.round(confidence)};if(exactReturn!=null)bet.importedPotentialReturns=Number(exactReturn);if(gaming)bet.manualProfitLoss=result==="Loss"?-Number(stake||0):result==="Void"?0:Number(exactReturn||0)-Number(stake||0);bets.push(bet)
    }
    const transactions=[];for(const g of groups){if(!inRange(g.date,from,to))continue;if(g.type!=="Deposit"&&g.type!=="Withdrawal")continue;const r=g.rows[0],amount=g.type==="Deposit"?(r.addition||0):(r.deduction||0);if(amount>0)transactions.push({date:g.date,when:g.when,app:"Bet365",type:g.type==="Deposit"?"deposit":"withdrawal",amount,sourceRef:g.ref||`${g.type}-${g.when}`})}
    const fromWhen=`${from}T00:00:00`,netAfterFrom=groups.flatMap(g=>g.rows).filter(r=>r.when>=fromWhen).reduce((s,r)=>s+(Number(r.addition)||0)-(Number(r.deduction)||0),0),opening=Number.isFinite(closingBalance)?closingBalance-netAfterFrom:null;
    return{bets,transactions,opening,closingBalance,groups}
  }
  async function ocrFullPage(doc,pageNo,w,status){
    status.textContent=`Reading Bet365 page ${pageNo}…`;const y0=pageNo===1?.58:.012,c=await renderCrop(doc,pageNo,2.55,y0,.94,.012,.995),r=await w.recognize(c),rows=wordsToRows(r.data,pageNo,c.width);c.width=c.height=1;return rows
  }
  async function statementSummary(doc,w,status){
    status.textContent="Reading Bet365 statement summary…";const c=await renderCrop(doc,1,2.25,.13,.60,.012,.72),r=await w.recognize(c),t=String(r.data?.text||"");c.width=c.height=1;if(!/bet365|Statement of All Transactions/i.test(t))throw new Error("That does not look like a Bet365 Statement of All Transactions PDF.");const m=t.match(/Closing\s+Balance\s+£?\s*([0-9,]+(?:\.\d{2})?)/i),s=t.match(/Starting\s+Balance\s+£?\s*([0-9,]+(?:\.\d{2})?)/i);return{closing:m?Number(m[1].replace(/,/g,"")):null,starting:s?Number(s[1].replace(/,/g,"")):null,text:t}
  }
  async function analyseBet365(){
    const panel=document.querySelector("#bt-import-bets"),status=panel?.querySelector("#bt-import-status"),btn=panel?.querySelector("#bt-read-import"),file=panel?.querySelector("#bt-import-statement")?.files?.[0],from=panel?.querySelector("#bt365-from")?.value,to=panel?.querySelector("#bt365-to")?.value;if(!status||!btn)return;if(!file){status.textContent="Choose the Bet365 statement PDF first.";status.className="bt-import-status err";return}if(!from||!to||from>to){status.textContent="Choose a valid From and To date first.";status.className="bt-import-status err";return}
    btn.disabled=true;status.className="bt-import-status";try{const pdf=await loadPdf(),doc=await pdf.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,w=await getWorker(status),summary=await statementSummary(doc,w,status),last=await findLastPageForFrom(doc,from,w,status);if(!last)throw new Error("No Bet365 transactions were found on or after that start date.");const allRows=[];for(let n=1;n<=last;n++){status.textContent=`Reading Bet365 page ${n} of ${last} needed for your dates…`;allRows.push(...await ocrFullPage(doc,n,w,status))}const groups=groupRows(allRows),built=buildData(groups,from,to,summary.closing);current={...built,from,to,pagesRead:last,totalPages:doc.numPages};if(!built.bets.length&&!built.transactions.length)throw new Error("No Bet365 bets or cash movements were found in those dates.");status.textContent=`Found ${built.bets.length} Bet365 bets and ${built.transactions.length} deposits/withdrawals.`;status.className="bt-import-status ok";renderPreview()}catch(e){console.error(e);status.textContent=e.message||"Could not read that Bet365 statement.";status.className="bt-import-status err"}finally{btn.disabled=false}
  }
  function likelyKey(b){return`${b.date}|${norm(b.app)}|${Number(b.stake||0).toFixed(2)}|${norm(b.description).replace(/\s+/g," ")}`}
  function renderPreview(){
    const p=document.querySelector("#bt-import-bets"),box=p?.querySelector("#bt-import-preview");if(!p||!box||!current)return;const rows=current.bets,cash=current.transactions,opening=current.opening,review=rows.filter(r=>r.importConfidence==="review").length;box.innerHTML=`<div class="bt-preview"><div class="bt-import-summary"><div><span>Bets found</span><strong>${rows.length}</strong></div><div><span>Auto-read</span><strong>${rows.length-review}</strong></div><div><span>Review suggested</span><strong>${review}</strong></div><div><span>Cash movements</span><strong>${cash.length}</strong></div></div><div class="bt-opening">Opening Bet365 balance at ${esc(current.from.split("-").reverse().join("/"))}: <strong>${opening==null?"Could not calculate":money(opening)}</strong></div><p class="bt-preview-note"><strong>Bet365 provides much richer data than Paddy Power:</strong> sport, event/market description, selection, odds, result, stake/return and cash movements are read from the statement. Because Bet365 supplies this statement as page images, Bet Tracker uses OCR and flags lower-confidence rows for review before import. ${current.pagesRead} of ${current.totalPages} pages were read for this date range and opening balance.</p><div class="bt-import-tools"><button class="button secondary" id="bt365-all">Select all</button><button class="button secondary" id="bt365-safe">Select auto-read</button><button class="button secondary" id="bt365-none">Select none</button><span class="muted" id="bt365-count"></span></div><div class="bt-import-table"><table><thead><tr><th></th><th>Date</th><th>Sport</th><th>Description</th><th>Odds</th><th>Stake</th><th>Result</th><th>Read</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td><input class="bt365-check" type="checkbox" data-i="${i}" checked></td><td>${esc(r.date)}</td><td>${esc(r.sport)}</td><td>${esc(r.description)}</td><td>${Number(r.odds||0).toFixed(2)}</td><td>${money(r.stake)}</td><td>${esc(r.result)}</td><td><span class="bt-conf ${r.importConfidence}">${r.importConfidence==="high"?"Auto-read":"Review"}</span></td></tr>`).join("")}</tbody></table></div><div class="bt-import-final"><div><label><input type="checkbox" id="bt365-cash" checked> Import deposits & withdrawals</label>${opening==null?"":`<label style="margin-top:7px"><input type="checkbox" id="bt365-opening" checked> Use ${money(opening)} as Bet365 starting balance</label>`}<label style="margin-top:7px"><input type="checkbox" id="bt365-dupes" checked> Skip likely duplicates</label></div><button class="button primary" id="bt365-confirm">Import selected Bet365 bets</button></div></div>`;
    const checks=[...box.querySelectorAll(".bt365-check")],count=()=>box.querySelector("#bt365-count").textContent=`${checks.filter(x=>x.checked).length} selected`;checks.forEach(x=>x.onchange=count);count();box.querySelector("#bt365-all").onclick=()=>{checks.forEach(x=>x.checked=true);count()};box.querySelector("#bt365-none").onclick=()=>{checks.forEach(x=>x.checked=false);count()};box.querySelector("#bt365-safe").onclick=()=>{checks.forEach(x=>x.checked=rows[Number(x.dataset.i)].importConfidence==="high");count()};box.querySelector("#bt365-confirm").onclick=doImport
  }
  async function doImport(){
    const p=document.querySelector("#bt-import-bets"),status=p?.querySelector("#bt-import-status"),btn=p?.querySelector("#bt365-confirm"),d=readData();if(!p||!status||!btn||!d||!current)return;btn.disabled=true;try{d.bets=Array.isArray(d.bets)?d.bets:[];d.transactions=Array.isArray(d.transactions)?d.transactions:[];d.bookmakerStartingBalances=d.bookmakerStartingBalances||{};d.customSports=Array.isArray(d.customSports)?d.customSports:[];const selected=new Set([...p.querySelectorAll(".bt365-check:checked")].map(x=>Number(x.dataset.i))),skip=p.querySelector("#bt365-dupes")?.checked!==false,refs=new Set(d.bets.map(b=>b.sourceRef).filter(Boolean)),keys=new Set(d.bets.map(likelyKey)),txrefs=new Set(d.transactions.map(t=>t.sourceRef).filter(Boolean));let added=0,dupes=0;current.bets.forEach((r,i)=>{if(!selected.has(i))return;const sr=`Bet365:${r.sourceRef}`,bet={id:`import-${hash(sr)}`,date:r.date,app:"Bet365",sport:r.sport,type:r.type,description:r.description,odds:Number(r.odds)||1,stake:Number(r.stake)||0,result:r.result||"Pending",createdAt:Date.parse(r.when),source:"Bet365 statement import",sourceRef:sr,importConfidence:r.importConfidence,ocrConfidence:r.ocrConfidence};if(r.importedPotentialReturns!=null)bet.importedPotentialReturns=Number(r.importedPotentialReturns);if(r.manualProfitLoss!=null)bet.manualProfitLoss=Number(r.manualProfitLoss);const k=likelyKey(bet);if(refs.has(sr)||(skip&&keys.has(k))){dupes++;return}d.bets.push(bet);refs.add(sr);keys.add(k);added++;if(bet.sport&&!['Football','Darts','Basketball','Free Spins'].includes(bet.sport)&&!d.customSports.includes(bet.sport))d.customSports.push(bet.sport)});let tx=0;if(p.querySelector("#bt365-cash")?.checked!==false)for(const r of current.transactions){const sr=`Bet365:${r.sourceRef}`;if(txrefs.has(sr))continue;d.transactions.push({id:`import-${hash(sr)}`,date:r.date,app:"Bet365",amount:Number(r.amount)||0,type:r.type,createdAt:Date.parse(r.when),source:"Bet365 statement import",sourceRef:sr});txrefs.add(sr);tx++}if(current.opening!=null&&p.querySelector("#bt365-opening")?.checked!==false)d.bookmakerStartingBalances["Bet365"]={amount:Number(current.opening)||0,date:current.from,source:"Bet365 statement"};await saveData(d);status.textContent=`Imported ${added} Bet365 bets and ${tx} cash movements${dupes?`; skipped ${dupes} duplicates`:""}. Refreshing…`;status.className="bt-import-status ok";setTimeout(()=>location.reload(),700)}catch(e){console.error(e);status.textContent=e.message||"Bet365 import failed.";status.className="bt-import-status err";btn.disabled=false}
  }
  function snapshotPaddy(p){if(paddySnapshot)return;const fileLabel=p.querySelector("#bt-import-statement")?.closest("label"),small=fileLabel?.querySelector("small"),read=p.querySelector("#bt-read-import");paddySnapshot={fileText:fileLabel?.childNodes?.[0]?.nodeValue||"Paddy Power statement PDF",small:small?.textContent||"",readText:read?.textContent||"Read statement"};paddyReadHandler=read?.onclick||null}
  function restorePaddy(p){
    if(!paddySnapshot)return;const fileLabel=p.querySelector("#bt-import-statement")?.closest("label"),small=fileLabel?.querySelector("small"),read=p.querySelector("#bt-read-import");p.querySelector("#bt365-note")?.remove();p.querySelector("#bt365-range")?.remove();if(fileLabel?.childNodes?.[0])fileLabel.childNodes[0].nodeValue=paddySnapshot.fileText;if(small)small.textContent=paddySnapshot.small;if(read){read.textContent=paddySnapshot.readText;if(paddyReadHandler)read.onclick=paddyReadHandler}p.querySelector(".bt-paddy-limit")?.style.removeProperty("display");p.querySelector("#bt-import-preview")?.replaceChildren();const st=p.querySelector("#bt-import-status");if(st){st.textContent="Nothing has been imported yet.";st.className="bt-import-status"}
  }
  window.bt365RestorePaddy=restorePaddy;
  window.bt365ConfigureImport=p=>{
    snapshotPaddy(p);const h=p.querySelector(".bt-import-head h2");if(h)h.textContent="Import Bet365 bets";const intro=p.querySelector(".bt-import-head p");if(intro)intro.textContent="Upload your Bet365 Statement of All Transactions, choose the dates you want and preview the OCR-read records before importing.";const fileLabel=p.querySelector("#bt-import-statement")?.closest("label"),small=fileLabel?.querySelector("small"),read=p.querySelector("#bt-read-import");if(fileLabel?.childNodes?.[0])fileLabel.childNodes[0].nodeValue="Bet365 statement PDF";if(small)small.textContent="Use Bet365's Statement of All Transactions PDF. The file is read in your browser and is not saved to Bet Tracker.";p.querySelector(".bt-paddy-limit")?.style.setProperty("display","none");if(!p.querySelector("#bt365-note")){const note=document.createElement("div");note.id="bt365-note";note.style.cssText="grid-column:1/-1;padding:12px 14px;border-radius:12px;background:rgba(46,103,240,.08);border:1px solid rgba(83,130,255,.22);color:#aebfd5;font-size:12px;line-height:1.55";note.innerHTML="<strong style='color:#e8f0ff'>What Bet365 provides:</strong> sport, event/market description, selection odds, result, stakes/returns, deposits and withdrawals. Bet365's PDF is image-based, so Bet Tracker reads it with OCR and shows a preview before anything is imported.";p.querySelector(".bt-import-grid")?.appendChild(note)}if(!p.querySelector("#bt365-range")){const r=document.createElement("div");r.id="bt365-range";r.style.cssText="grid-column:1/-1;display:grid;grid-template-columns:repeat(2,minmax(0,220px));gap:12px";r.innerHTML=`<label style="display:flex;flex-direction:column;gap:7px;font-size:12px;font-weight:700;color:#b8c6d9">Import from<input id="bt365-from" type="date" style="background:#07182e;color:#eef4ff;border:1px solid #263d5f;border-radius:10px;padding:11px 12px"></label><label style="display:flex;flex-direction:column;gap:7px;font-size:12px;font-weight:700;color:#b8c6d9">Import to<input id="bt365-to" type="date" style="background:#07182e;color:#eef4ff;border:1px solid #263d5f;border-radius:10px;padding:11px 12px"></label>`;p.querySelector(".bt-import-grid")?.appendChild(r)}if(read){read.textContent="Read Bet365 statement";read.onclick=analyseBet365}p.querySelector("#bt-import-preview")?.replaceChildren();const st=p.querySelector("#bt-import-status");if(st){st.textContent="Choose the statement and dates, then read it. Large history ranges can take a few minutes because Bet365 supplies page images.";st.className="bt-import-status"}
  };
})();
